#language: "zh"
#
#pipeline: "tensorflow_embedding"

language: "zh"

pipeline:
#- name: "tokenizer_whitespace"
#- name: "ner_crf"
#- name: "ner_synonyms"
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: True
  intent_split_symbol: "_"
  similarity_type: "cosine"